ALTER TABLE comments
    DROP FOREIGN KEY FK_COMMENTS_ON_BASE_USER;
ALTER TABLE comments
    DROP FOREIGN KEY FK_COMMENTS_ON_LESSON;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_BASE_USER FOREIGN KEY (base_user_id) REFERENCES base_users (id) ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE;