import * as matIcons from '@ng-icons/material-icons/round';

export const materialIcons = {
  matEmailRound: matIcons.matEmailRound,
  matLockRound: matIcons.matLockRound,
  matLoginRound: matIcons.matLoginRound,
  matLogoutRound: matIcons.matLogoutRound,
  matVisibilityOffRound: matIcons.matVisibilityOffRound,
  matVisibilityRound: matIcons.matVisibilityRound,
  matSyncRound: matIcons.matSyncRound,
  matToggleOffRound: matIcons.matToggleOffRound,
  matToggleOnRound: matIcons.matToggleOnRound,
  matSearchRound: matIcons.matSearchRound,
  matArrowOutwardRound: matIcons.matArrowOutwardRound,
  matHomeRound: matIcons.matHomeRound,
  matKeyboardDoubleArrowLeftRound: matIcons.matKeyboardDoubleArrowLeftRound,
  matKeyboardDoubleArrowRightRound: matIcons.matKeyboardDoubleArrowRightRound,
  matLeaderboardRound: matIcons.matLeaderboardRound,
  matLibraryBooksRound: matIcons.matLibraryBooksRound,
  matPersonRound: matIcons.matPersonRound,
  matQuizRound: matIcons.matQuizRound,
  matSettingsRound: matIcons.matSettingsRound,
  matSupervisorAccountRound: matIcons.matSupervisorAccountRound,
  matAddRound: matIcons.matAddRound,
  matCloseRound: matIcons.matCloseRound,
  matDeleteRound: matIcons.matDeleteRound,
  matEditRound: matIcons.matEditRound,
  matFilterListRound: matIcons.matFilterListRound,
  matInfoRound: matIcons.matInfoRound,
  matLockOpenRound: matIcons.matLockOpenRound,
  matSaveRound: matIcons.matSaveRound,
  matKeyboardArrowLeftRound: matIcons.matKeyboardArrowLeftRound,
  matKeyboardArrowRightRound: matIcons.matKeyboardArrowRightRound,
  matDoneRound: matIcons.matDoneRound,
  matQuestionMarkRound: matIcons.matQuestionMarkRound,
  matCheckCircleRound: matIcons.matCheckCircleRound,
  matCancelRound: matIcons.matCancelRound,
  matGroupsRound: matIcons.matGroupsRound,
  matAssistantRound: matIcons.matAssistantRound,
  matStarsRound: matIcons.matStarsRound,
  matMemoryRound: matIcons.matMemoryRound,
  matMenuRound: matIcons.matMenuRound,
  matSendRound: matIcons.matSendRound,
  matContentCopyRound: matIcons.matContentCopyRound,
  matExpandMoreRound: matIcons.matExpandMoreRound,
  matAttachFileRound: matIcons.matAttachFileRound,
  matPersonAddRound: matIcons.matPersonAddRound,
};
